language: node_js
node_js:
  - "6"
before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  local_dir: dist
  repo: MarxJiao/d3-demos
  skip_cleanup: true
  github_token: $GIT
  on:
    branch: master
  target_branch: gh-pages